### PR TITLE
Enabled NuGet Package Restore for DDD Session Tests

### PR DESCRIPTION
**Pull request by eric-davis**
Enabled the NuGet package restore functionality for the DDD Session Tests project to correct initial solution build errors.

### CODE REVIEW

**Comment by julielerman** [comment]
oh thanks. Can't believe I forgot that one. Did I even remember to clean the solution (git clean dlx or whatever that command is)? I was trying to do too much at once! :)

**Comment by eric-davis** [comment]
No problem. That was the only thing I noticed. After having gone through your Pluralsight course, I'm just happy to see this example solution made available. Thank you! :-)

**Comment by huytnd** [comment]
Do you have any plan to make a version using EF7?

**Comment by julielerman** [comment]
Not at the moment since EF7 doesn't support everything I need to emulate this. Doing more exploratory work with EF7 atm.

**Pull request merged**
